" Use intelligent indenting based on filetype
filetype indent plugin on

" Syntax highlighting
syntax on

" Raise a dialog to ask if you want to save a changed file instead of failing
set confirm

" Line numbers
set number

" Indentation settings
set shiftwidth=2
set softtabstop=2
set expandtab
set backspace=indent,eol,start

" Remap <esc> to jj so get around touchbar
inoremap jj <Esc>

" Use a thinner line for indentLine
let g:indentLine_char = '⦙'

" Use popup windows for godoc
let g:go_doc_popup_window = 1

" Use TAB to trigger an autocompletion
inoremap <expr> <Tab> pumvisible() ? "<C-N>" : "<C-R>=completor#do('complete')<CR>"

" Cycle through completion options with TAB/Shift+TAB
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Configure maralla/completor to use gopls for autocompletion
let g:completor_auto_trigger = 1
let g:completor_filetype_map = {}
let g:completor_filetype_map.go = {'ft': 'lsp', 'cmd': 'gopls -remote=auto'}
